//// <auto-generated />
//using System;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using NotesApplication.Data;

//#nullable disable

//namespace NotesApplication.Data.Migrations
//{
//    [DbContext(typeof(NotesDbContext))]
//    [Migration("20240428120123_InsertedRoles")]
//    partial class InsertedRoles
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "8.0.4")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
//                {
//                    b.Property<string>("Id")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("ConcurrencyStamp")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Name")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("NormalizedName")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("IdentityRole");

//                    b.HasData(
//                        new
//                        {
//                            Id = "81ff889b-83ba-4920-b9b1-c36b4279e51d",
//                            Name = "Visitor",
//                            NormalizedName = "VISITOR"
//                        },
//                        new
//                        {
//                            Id = "c2f21312-584a-475e-90f7-d49b57b4ca69",
//                            Name = "Administrator",
//                            NormalizedName = "ADMINISTRATOR"
//                        });
//                });

//            modelBuilder.Entity("NotesApplication.Core.Note", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("Description")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("Time")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.ToTable("Notes");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
